namespace DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddColumnsToBaseEntity : DbMigration
    {
        public override void Up()
        {
            AddColumn("COMPONENT.BackPlane", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.BackPlane", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.BackPlane", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Brand", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Brand", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Brand", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Manager", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Manager", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Manager", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.EthernetCard", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.EthernetCard", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.EthernetCard", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.FiberCard", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.FiberCard", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.FiberCard", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Harddisk", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Harddisk", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Harddisk", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.HddCady", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.HddCady", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.HddCady", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.HeatSink", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.HeatSink", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.HeatSink", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.KVM", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.KVM", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.KVM", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.LED", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.LED", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.LED", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Memory", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Memory", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Memory", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.MotherBroad", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.MotherBroad", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.MotherBroad", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.PDU", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.PDU", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.PDU", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.PowerSupply", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.PowerSupply", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.PowerSupply", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Processor", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Processor", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Processor", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Rack", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Rack", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Rack", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RaidBattery", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RaidBattery", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RaidBattery", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RaidCard", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RaidCard", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RaidCard", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RaidMemory", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RaidMemory", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RaidMemory", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RailKit", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RailKit", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RailKit", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RiserCard", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RiserCard", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.RiserCard", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.SAASCable", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.SAASCable", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.SAASCable", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.SFP", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.SFP", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.SFP", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Storage", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Storage", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Storage", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Switch", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Switch", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.Switch", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.TFTConsole", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.TFTConsole", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.TFTConsole", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.ThinClient", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.ThinClient", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.ThinClient", "PurchasingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.ZeroClient", "SellingPrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.ZeroClient", "AveragePrice", c => c.Double(nullable: false));
            AddColumn("COMPONENT.ZeroClient", "PurchasingPrice", c => c.Double(nullable: false));
            DropColumn("COMPONENT.BackPlane", "PurchaseDate");
            DropColumn("COMPONENT.BackPlane", "ModifiedDate");
            DropColumn("COMPONENT.Brand", "PurchaseDate");
            DropColumn("COMPONENT.Brand", "ModifiedDate");
            DropColumn("COMPONENT.Manager", "PurchaseDate");
            DropColumn("COMPONENT.Manager", "ModifiedDate");
            DropColumn("COMPONENT.EthernetCard", "PurchaseDate");
            DropColumn("COMPONENT.EthernetCard", "ModifiedDate");
            DropColumn("COMPONENT.FiberCard", "PurchaseDate");
            DropColumn("COMPONENT.FiberCard", "ModifiedDate");
            DropColumn("COMPONENT.Harddisk", "PurchaseDate");
            DropColumn("COMPONENT.Harddisk", "ModifiedDate");
            DropColumn("COMPONENT.HddCady", "PurchaseDate");
            DropColumn("COMPONENT.HddCady", "ModifiedDate");
            DropColumn("COMPONENT.HeatSink", "PurchaseDate");
            DropColumn("COMPONENT.HeatSink", "ModifiedDate");
            DropColumn("COMPONENT.KVM", "PurchaseDate");
            DropColumn("COMPONENT.KVM", "ModifiedDate");
            DropColumn("COMPONENT.LED", "PurchaseDate");
            DropColumn("COMPONENT.LED", "ModifiedDate");
            DropColumn("COMPONENT.Memory", "PurchaseDate");
            DropColumn("COMPONENT.Memory", "ModifiedDate");
            DropColumn("COMPONENT.MotherBroad", "PurchaseDate");
            DropColumn("COMPONENT.MotherBroad", "ModifiedDate");
            DropColumn("COMPONENT.PDU", "PurchaseDate");
            DropColumn("COMPONENT.PDU", "ModifiedDate");
            DropColumn("COMPONENT.PowerSupply", "PurchaseDate");
            DropColumn("COMPONENT.PowerSupply", "ModifiedDate");
            DropColumn("COMPONENT.Processor", "PurchaseDate");
            DropColumn("COMPONENT.Processor", "ModifiedDate");
            DropColumn("COMPONENT.Rack", "PurchaseDate");
            DropColumn("COMPONENT.Rack", "ModifiedDate");
            DropColumn("COMPONENT.RaidBattery", "PurchaseDate");
            DropColumn("COMPONENT.RaidBattery", "ModifiedDate");
            DropColumn("COMPONENT.RaidCard", "PurchaseDate");
            DropColumn("COMPONENT.RaidCard", "ModifiedDate");
            DropColumn("COMPONENT.RaidMemory", "PurchaseDate");
            DropColumn("COMPONENT.RaidMemory", "ModifiedDate");
            DropColumn("COMPONENT.RailKit", "PurchaseDate");
            DropColumn("COMPONENT.RailKit", "ModifiedDate");
            DropColumn("COMPONENT.RiserCard", "PurchaseDate");
            DropColumn("COMPONENT.RiserCard", "ModifiedDate");
            DropColumn("COMPONENT.SAASCable", "PurchaseDate");
            DropColumn("COMPONENT.SAASCable", "ModifiedDate");
            DropColumn("COMPONENT.SFP", "PurchaseDate");
            DropColumn("COMPONENT.SFP", "ModifiedDate");
            DropColumn("COMPONENT.Storage", "PurchaseDate");
            DropColumn("COMPONENT.Storage", "ModifiedDate");
            DropColumn("COMPONENT.Switch", "PurchaseDate");
            DropColumn("COMPONENT.Switch", "ModifiedDate");
            DropColumn("COMPONENT.TFTConsole", "PurchaseDate");
            DropColumn("COMPONENT.TFTConsole", "ModifiedDate");
            DropColumn("COMPONENT.ThinClient", "PurchaseDate");
            DropColumn("COMPONENT.ThinClient", "ModifiedDate");
            DropColumn("COMPONENT.ZeroClient", "PurchaseDate");
            DropColumn("COMPONENT.ZeroClient", "ModifiedDate");
        }
        
        public override void Down()
        {
            AddColumn("COMPONENT.ZeroClient", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.ZeroClient", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.ThinClient", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.ThinClient", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.TFTConsole", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.TFTConsole", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Switch", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Switch", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Storage", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Storage", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.SFP", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.SFP", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.SAASCable", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.SAASCable", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.RiserCard", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.RiserCard", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.RailKit", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.RailKit", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.RaidMemory", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.RaidMemory", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.RaidCard", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.RaidCard", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.RaidBattery", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.RaidBattery", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Rack", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Rack", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Processor", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Processor", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.PowerSupply", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.PowerSupply", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.PDU", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.PDU", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.MotherBroad", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.MotherBroad", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Memory", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Memory", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.LED", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.LED", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.KVM", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.KVM", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.HeatSink", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.HeatSink", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.HddCady", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.HddCady", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Harddisk", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Harddisk", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.FiberCard", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.FiberCard", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.EthernetCard", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.EthernetCard", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Manager", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Manager", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Brand", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Brand", "PurchaseDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.BackPlane", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.BackPlane", "PurchaseDate", c => c.DateTime(nullable: false));
            DropColumn("COMPONENT.ZeroClient", "PurchasingPrice");
            DropColumn("COMPONENT.ZeroClient", "AveragePrice");
            DropColumn("COMPONENT.ZeroClient", "SellingPrice");
            DropColumn("COMPONENT.ThinClient", "PurchasingPrice");
            DropColumn("COMPONENT.ThinClient", "AveragePrice");
            DropColumn("COMPONENT.ThinClient", "SellingPrice");
            DropColumn("COMPONENT.TFTConsole", "PurchasingPrice");
            DropColumn("COMPONENT.TFTConsole", "AveragePrice");
            DropColumn("COMPONENT.TFTConsole", "SellingPrice");
            DropColumn("COMPONENT.Switch", "PurchasingPrice");
            DropColumn("COMPONENT.Switch", "AveragePrice");
            DropColumn("COMPONENT.Switch", "SellingPrice");
            DropColumn("COMPONENT.Storage", "PurchasingPrice");
            DropColumn("COMPONENT.Storage", "AveragePrice");
            DropColumn("COMPONENT.Storage", "SellingPrice");
            DropColumn("COMPONENT.SFP", "PurchasingPrice");
            DropColumn("COMPONENT.SFP", "AveragePrice");
            DropColumn("COMPONENT.SFP", "SellingPrice");
            DropColumn("COMPONENT.SAASCable", "PurchasingPrice");
            DropColumn("COMPONENT.SAASCable", "AveragePrice");
            DropColumn("COMPONENT.SAASCable", "SellingPrice");
            DropColumn("COMPONENT.RiserCard", "PurchasingPrice");
            DropColumn("COMPONENT.RiserCard", "AveragePrice");
            DropColumn("COMPONENT.RiserCard", "SellingPrice");
            DropColumn("COMPONENT.RailKit", "PurchasingPrice");
            DropColumn("COMPONENT.RailKit", "AveragePrice");
            DropColumn("COMPONENT.RailKit", "SellingPrice");
            DropColumn("COMPONENT.RaidMemory", "PurchasingPrice");
            DropColumn("COMPONENT.RaidMemory", "AveragePrice");
            DropColumn("COMPONENT.RaidMemory", "SellingPrice");
            DropColumn("COMPONENT.RaidCard", "PurchasingPrice");
            DropColumn("COMPONENT.RaidCard", "AveragePrice");
            DropColumn("COMPONENT.RaidCard", "SellingPrice");
            DropColumn("COMPONENT.RaidBattery", "PurchasingPrice");
            DropColumn("COMPONENT.RaidBattery", "AveragePrice");
            DropColumn("COMPONENT.RaidBattery", "SellingPrice");
            DropColumn("COMPONENT.Rack", "PurchasingPrice");
            DropColumn("COMPONENT.Rack", "AveragePrice");
            DropColumn("COMPONENT.Rack", "SellingPrice");
            DropColumn("COMPONENT.Processor", "PurchasingPrice");
            DropColumn("COMPONENT.Processor", "AveragePrice");
            DropColumn("COMPONENT.Processor", "SellingPrice");
            DropColumn("COMPONENT.PowerSupply", "PurchasingPrice");
            DropColumn("COMPONENT.PowerSupply", "AveragePrice");
            DropColumn("COMPONENT.PowerSupply", "SellingPrice");
            DropColumn("COMPONENT.PDU", "PurchasingPrice");
            DropColumn("COMPONENT.PDU", "AveragePrice");
            DropColumn("COMPONENT.PDU", "SellingPrice");
            DropColumn("COMPONENT.MotherBroad", "PurchasingPrice");
            DropColumn("COMPONENT.MotherBroad", "AveragePrice");
            DropColumn("COMPONENT.MotherBroad", "SellingPrice");
            DropColumn("COMPONENT.Memory", "PurchasingPrice");
            DropColumn("COMPONENT.Memory", "AveragePrice");
            DropColumn("COMPONENT.Memory", "SellingPrice");
            DropColumn("COMPONENT.LED", "PurchasingPrice");
            DropColumn("COMPONENT.LED", "AveragePrice");
            DropColumn("COMPONENT.LED", "SellingPrice");
            DropColumn("COMPONENT.KVM", "PurchasingPrice");
            DropColumn("COMPONENT.KVM", "AveragePrice");
            DropColumn("COMPONENT.KVM", "SellingPrice");
            DropColumn("COMPONENT.HeatSink", "PurchasingPrice");
            DropColumn("COMPONENT.HeatSink", "AveragePrice");
            DropColumn("COMPONENT.HeatSink", "SellingPrice");
            DropColumn("COMPONENT.HddCady", "PurchasingPrice");
            DropColumn("COMPONENT.HddCady", "AveragePrice");
            DropColumn("COMPONENT.HddCady", "SellingPrice");
            DropColumn("COMPONENT.Harddisk", "PurchasingPrice");
            DropColumn("COMPONENT.Harddisk", "AveragePrice");
            DropColumn("COMPONENT.Harddisk", "SellingPrice");
            DropColumn("COMPONENT.FiberCard", "PurchasingPrice");
            DropColumn("COMPONENT.FiberCard", "AveragePrice");
            DropColumn("COMPONENT.FiberCard", "SellingPrice");
            DropColumn("COMPONENT.EthernetCard", "PurchasingPrice");
            DropColumn("COMPONENT.EthernetCard", "AveragePrice");
            DropColumn("COMPONENT.EthernetCard", "SellingPrice");
            DropColumn("COMPONENT.Manager", "PurchasingPrice");
            DropColumn("COMPONENT.Manager", "AveragePrice");
            DropColumn("COMPONENT.Manager", "SellingPrice");
            DropColumn("COMPONENT.Brand", "PurchasingPrice");
            DropColumn("COMPONENT.Brand", "AveragePrice");
            DropColumn("COMPONENT.Brand", "SellingPrice");
            DropColumn("COMPONENT.BackPlane", "PurchasingPrice");
            DropColumn("COMPONENT.BackPlane", "AveragePrice");
            DropColumn("COMPONENT.BackPlane", "SellingPrice");
        }
    }
}
