namespace DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddBaseEntityTracking : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("COMPONENT.Harddisk", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.HddCady", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.KVM", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.LED", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.Memory", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.PDU", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.PowerSupply", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.RaidCard", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.RaidMemory", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.RailKit", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.SAASCable", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.Storage", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.TFTConsole", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.ThinClient", "BrandId", "COMPONENT.Brand");
            DropForeignKey("COMPONENT.ZeroClient", "BrandId", "COMPONENT.Brand");
            DropIndex("COMPONENT.Harddisk", new[] { "BrandId" });
            DropIndex("COMPONENT.HddCady", new[] { "BrandId" });
            DropIndex("COMPONENT.KVM", new[] { "BrandId" });
            DropIndex("COMPONENT.LED", new[] { "BrandId" });
            DropIndex("COMPONENT.Memory", new[] { "BrandId" });
            DropIndex("COMPONENT.PDU", new[] { "BrandId" });
            DropIndex("COMPONENT.PowerSupply", new[] { "BrandId" });
            DropIndex("COMPONENT.RaidCard", new[] { "BrandId" });
            DropIndex("COMPONENT.RaidMemory", new[] { "BrandId" });
            DropIndex("COMPONENT.RailKit", new[] { "BrandId" });
            DropIndex("COMPONENT.SAASCable", new[] { "BrandId" });
            DropIndex("COMPONENT.Storage", new[] { "BrandId" });
            DropIndex("COMPONENT.TFTConsole", new[] { "BrandId" });
            DropIndex("COMPONENT.ThinClient", new[] { "BrandId" });
            DropIndex("COMPONENT.ZeroClient", new[] { "BrandId" });
            AddColumn("COMPONENT.BackPlane", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.BackPlane", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Brand", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Brand", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.EthernetCard", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.EthernetCard", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.FiberCard", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.FiberCard", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Harddisk", "Brand", c => c.String());
            AddColumn("COMPONENT.Harddisk", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Harddisk", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.HddCady", "Brand", c => c.String());
            AddColumn("COMPONENT.HddCady", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.HddCady", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.HeatSink", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.HeatSink", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.KVM", "Brand", c => c.String());
            AddColumn("COMPONENT.KVM", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.KVM", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.LED", "Brand", c => c.String());
            AddColumn("COMPONENT.LED", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.LED", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Memory", "Brand", c => c.String());
            AddColumn("COMPONENT.Memory", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Memory", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.MotherBroad", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.MotherBroad", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.PDU", "Brand", c => c.String());
            AddColumn("COMPONENT.PDU", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.PDU", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.PowerSupply", "Brand", c => c.String());
            AddColumn("COMPONENT.PowerSupply", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.PowerSupply", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Processor", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Processor", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Rack", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Rack", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.RaidBattery", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.RaidBattery", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.RaidCard", "Brand", c => c.String());
            AddColumn("COMPONENT.RaidCard", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.RaidCard", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.RaidMemory", "Brand", c => c.String());
            AddColumn("COMPONENT.RaidMemory", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.RaidMemory", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.RailKit", "Brand", c => c.String());
            AddColumn("COMPONENT.RailKit", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.RailKit", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.RiserCard", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.RiserCard", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.SAASCable", "Brand", c => c.String());
            AddColumn("COMPONENT.SAASCable", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.SAASCable", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.SFP", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.SFP", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Storage", "Brand", c => c.String());
            AddColumn("COMPONENT.Storage", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Storage", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.Switch", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.Switch", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.TFTConsole", "Brand", c => c.String());
            AddColumn("COMPONENT.TFTConsole", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.TFTConsole", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.ThinClient", "Brand", c => c.String());
            AddColumn("COMPONENT.ThinClient", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.ThinClient", "ModifiedDate", c => c.DateTime());
            AddColumn("COMPONENT.ZeroClient", "Brand", c => c.String());
            AddColumn("COMPONENT.ZeroClient", "CreatedDate", c => c.DateTime(nullable: false));
            AddColumn("COMPONENT.ZeroClient", "ModifiedDate", c => c.DateTime());
            DropColumn("COMPONENT.Harddisk", "BrandId");
            DropColumn("COMPONENT.HddCady", "BrandId");
            DropColumn("COMPONENT.KVM", "BrandId");
            DropColumn("COMPONENT.LED", "BrandId");
            DropColumn("COMPONENT.Memory", "BrandId");
            DropColumn("COMPONENT.PDU", "BrandId");
            DropColumn("COMPONENT.PowerSupply", "BrandId");
            DropColumn("COMPONENT.RaidCard", "BrandId");
            DropColumn("COMPONENT.RaidMemory", "BrandId");
            DropColumn("COMPONENT.RailKit", "BrandId");
            DropColumn("COMPONENT.SAASCable", "BrandId");
            DropColumn("COMPONENT.Storage", "BrandId");
            DropColumn("COMPONENT.TFTConsole", "BrandId");
            DropColumn("COMPONENT.ThinClient", "BrandId");
            DropColumn("COMPONENT.ZeroClient", "BrandId");
        }
        
        public override void Down()
        {
            AddColumn("COMPONENT.ZeroClient", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.ThinClient", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.TFTConsole", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.Storage", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.SAASCable", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.RailKit", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.RaidMemory", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.RaidCard", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.PowerSupply", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.PDU", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.Memory", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.LED", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.KVM", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.HddCady", "BrandId", c => c.Long(nullable: false));
            AddColumn("COMPONENT.Harddisk", "BrandId", c => c.Long(nullable: false));
            DropColumn("COMPONENT.ZeroClient", "ModifiedDate");
            DropColumn("COMPONENT.ZeroClient", "CreatedDate");
            DropColumn("COMPONENT.ZeroClient", "Brand");
            DropColumn("COMPONENT.ThinClient", "ModifiedDate");
            DropColumn("COMPONENT.ThinClient", "CreatedDate");
            DropColumn("COMPONENT.ThinClient", "Brand");
            DropColumn("COMPONENT.TFTConsole", "ModifiedDate");
            DropColumn("COMPONENT.TFTConsole", "CreatedDate");
            DropColumn("COMPONENT.TFTConsole", "Brand");
            DropColumn("COMPONENT.Switch", "ModifiedDate");
            DropColumn("COMPONENT.Switch", "CreatedDate");
            DropColumn("COMPONENT.Storage", "ModifiedDate");
            DropColumn("COMPONENT.Storage", "CreatedDate");
            DropColumn("COMPONENT.Storage", "Brand");
            DropColumn("COMPONENT.SFP", "ModifiedDate");
            DropColumn("COMPONENT.SFP", "CreatedDate");
            DropColumn("COMPONENT.SAASCable", "ModifiedDate");
            DropColumn("COMPONENT.SAASCable", "CreatedDate");
            DropColumn("COMPONENT.SAASCable", "Brand");
            DropColumn("COMPONENT.RiserCard", "ModifiedDate");
            DropColumn("COMPONENT.RiserCard", "CreatedDate");
            DropColumn("COMPONENT.RailKit", "ModifiedDate");
            DropColumn("COMPONENT.RailKit", "CreatedDate");
            DropColumn("COMPONENT.RailKit", "Brand");
            DropColumn("COMPONENT.RaidMemory", "ModifiedDate");
            DropColumn("COMPONENT.RaidMemory", "CreatedDate");
            DropColumn("COMPONENT.RaidMemory", "Brand");
            DropColumn("COMPONENT.RaidCard", "ModifiedDate");
            DropColumn("COMPONENT.RaidCard", "CreatedDate");
            DropColumn("COMPONENT.RaidCard", "Brand");
            DropColumn("COMPONENT.RaidBattery", "ModifiedDate");
            DropColumn("COMPONENT.RaidBattery", "CreatedDate");
            DropColumn("COMPONENT.Rack", "ModifiedDate");
            DropColumn("COMPONENT.Rack", "CreatedDate");
            DropColumn("COMPONENT.Processor", "ModifiedDate");
            DropColumn("COMPONENT.Processor", "CreatedDate");
            DropColumn("COMPONENT.PowerSupply", "ModifiedDate");
            DropColumn("COMPONENT.PowerSupply", "CreatedDate");
            DropColumn("COMPONENT.PowerSupply", "Brand");
            DropColumn("COMPONENT.PDU", "ModifiedDate");
            DropColumn("COMPONENT.PDU", "CreatedDate");
            DropColumn("COMPONENT.PDU", "Brand");
            DropColumn("COMPONENT.MotherBroad", "ModifiedDate");
            DropColumn("COMPONENT.MotherBroad", "CreatedDate");
            DropColumn("COMPONENT.Memory", "ModifiedDate");
            DropColumn("COMPONENT.Memory", "CreatedDate");
            DropColumn("COMPONENT.Memory", "Brand");
            DropColumn("COMPONENT.LED", "ModifiedDate");
            DropColumn("COMPONENT.LED", "CreatedDate");
            DropColumn("COMPONENT.LED", "Brand");
            DropColumn("COMPONENT.KVM", "ModifiedDate");
            DropColumn("COMPONENT.KVM", "CreatedDate");
            DropColumn("COMPONENT.KVM", "Brand");
            DropColumn("COMPONENT.HeatSink", "ModifiedDate");
            DropColumn("COMPONENT.HeatSink", "CreatedDate");
            DropColumn("COMPONENT.HddCady", "ModifiedDate");
            DropColumn("COMPONENT.HddCady", "CreatedDate");
            DropColumn("COMPONENT.HddCady", "Brand");
            DropColumn("COMPONENT.Harddisk", "ModifiedDate");
            DropColumn("COMPONENT.Harddisk", "CreatedDate");
            DropColumn("COMPONENT.Harddisk", "Brand");
            DropColumn("COMPONENT.FiberCard", "ModifiedDate");
            DropColumn("COMPONENT.FiberCard", "CreatedDate");
            DropColumn("COMPONENT.EthernetCard", "ModifiedDate");
            DropColumn("COMPONENT.EthernetCard", "CreatedDate");
            DropColumn("COMPONENT.Brand", "ModifiedDate");
            DropColumn("COMPONENT.Brand", "CreatedDate");
            DropColumn("COMPONENT.BackPlane", "ModifiedDate");
            DropColumn("COMPONENT.BackPlane", "CreatedDate");
            CreateIndex("COMPONENT.ZeroClient", "BrandId");
            CreateIndex("COMPONENT.ThinClient", "BrandId");
            CreateIndex("COMPONENT.TFTConsole", "BrandId");
            CreateIndex("COMPONENT.Storage", "BrandId");
            CreateIndex("COMPONENT.SAASCable", "BrandId");
            CreateIndex("COMPONENT.RailKit", "BrandId");
            CreateIndex("COMPONENT.RaidMemory", "BrandId");
            CreateIndex("COMPONENT.RaidCard", "BrandId");
            CreateIndex("COMPONENT.PowerSupply", "BrandId");
            CreateIndex("COMPONENT.PDU", "BrandId");
            CreateIndex("COMPONENT.Memory", "BrandId");
            CreateIndex("COMPONENT.LED", "BrandId");
            CreateIndex("COMPONENT.KVM", "BrandId");
            CreateIndex("COMPONENT.HddCady", "BrandId");
            CreateIndex("COMPONENT.Harddisk", "BrandId");
            AddForeignKey("COMPONENT.ZeroClient", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.ThinClient", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.TFTConsole", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.Storage", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.SAASCable", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.RailKit", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.RaidMemory", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.RaidCard", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.PowerSupply", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.PDU", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.Memory", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.LED", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.KVM", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.HddCady", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
            AddForeignKey("COMPONENT.Harddisk", "BrandId", "COMPONENT.Brand", "Id", cascadeDelete: true);
        }
    }
}
